server:
  port: 8081
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      maximum-pool-size: 6
      minimum-idle: 2
      connection-timeout: 10000
  application:
    name: adder

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        hbm2ddl:
          auto: validate
  mandatory-file-encoding: utf-8

logging:
  level:
    root: WARN
    ru: DEBUG

bot:
  token: 1189543200:AAHh_yaCt37hnXIm5oNrF5RL8wMKfThWoSo
  name: GerchPhotoTestbot
